### ISSUE TITLE
Emoji spelled incorrectly

### ISSUE THREAD

**Issue by ballardaudio** [robbiet480/emojovoto#1]
**Reproduction**

1. Follow steps outlined in the process section of README.md.
2. In you emoji voting channel, observe the output.

**Expected Result**
Proper terminology of "Emoji" is used.

**Actual Result**
Incorrect terminology of "Emojo" is used.

**Notes**
This error is also present in the name of the bot.

**Comment by robbiet480** [comment]
Behavior is intentional, closing as such.
